import { MD3DarkTheme } from 'react-native-paper';

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#60A5FA',
    primaryContainer: '#1E3A8A',
    secondary: '#A78BFA',
    secondaryContainer: '#4C1D95',
    tertiary: '#34D399',
    tertiaryContainer: '#065F46',
    surface: '#1F2937',
    surfaceVariant: '#374151',
    background: '#111827',
    error: '#F87171',
    errorContainer: '#7F1D1D',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onTertiary: '#000000',
    onSurface: '#F9FAFB',
    onSurfaceVariant: '#D1D5DB',
    onBackground: '#F9FAFB',
    onError: '#000000',
    outline: '#6B7280',
    outlineVariant: '#4B5563',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#F9FAFB',
    inverseOnSurface: '#1F2937',
    inversePrimary: '#1E40AF',
    elevation: {
      level0: 'transparent',
      level1: '#1F2937',
      level2: '#374151',
      level3: '#4B5563',
      level4: '#6B7280',
      level5: '#9CA3AF',
    },
    // Custom colors for Journi (dark mode)
    accent: '#FBBF24',
    accentContainer: '#92400E',
    success: '#34D399',
    successContainer: '#065F46',
    warning: '#FBBF24',
    warningContainer: '#92400E',
    info: '#60A5FA',
    infoContainer: '#1E3A8A',
    // Travel-specific colors (dark mode)
    beach: '#38BDF8',
    mountain: '#34D399',
    city: '#A78BFA',
    food: '#FBBF24',
    culture: '#F87171',
    adventure: '#F97316',
    luxury: '#EC4899',
    budget: '#34D399',
  },
  fonts: {
    ...MD3DarkTheme.fonts,
    displayLarge: {
      fontFamily: 'Inter_700Bold',
      fontSize: 57,
      fontWeight: '700',
      letterSpacing: -0.25,
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'Inter_700Bold',
      fontSize: 45,
      fontWeight: '700',
      letterSpacing: 0,
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 36,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 32,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 28,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 24,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 32,
    },
    titleLarge: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 22,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 16,
      fontWeight: '600',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 14,
      fontWeight: '600',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    bodyLarge: {
      fontFamily: 'Inter_400Regular',
      fontSize: 16,
      fontWeight: '400',
      letterSpacing: 0.5,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'Inter_400Regular',
      fontSize: 14,
      fontWeight: '400',
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'Inter_400Regular',
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    labelLarge: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 14,
      fontWeight: '600',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
  },
  roundness: 12,
}; 