import { MD3LightTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#5A67D8',
    primaryContainer: '#E6E8FF',
    secondary: '#ECC94B',
    secondaryContainer: '#FEF5E7',
    tertiary: '#38B2AC',
    tertiaryContainer: '#E6FFFA',
    surface: '#FFFFFF',
    surfaceVariant: '#F8FAFC',
    background: '#F8FAFC',
    error: '#E53E3E',
    onPrimary: '#FFFFFF',
    onSecondary: '#1A202C',
    onSurface: '#1F2937',
    onSurfaceVariant: '#6B7280',
    outline: '#E2E8F0',
    outlineVariant: '#F1F5F9',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#1F2937',
    inverseOnSurface: '#FFFFFF',
    inversePrimary: '#C7D2FE',
    elevation: {
      level0: 'transparent',
      level1: '#FFFFFF',
      level2: '#FFFFFF',
      level3: '#FFFFFF',
      level4: '#FFFFFF',
      level5: '#FFFFFF',
    },
    surfaceDisabled: '#F1F5F9',
    onSurfaceDisabled: '#9CA3AF',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: {
    ...MD3LightTheme.fonts,
    // Use system fonts for better performance
    displayLarge: {
      fontFamily: 'Inter_700Bold',
      fontSize: 57,
      fontWeight: '700',
      letterSpacing: -0.25,
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'Inter_700Bold',
      fontSize: 45,
      fontWeight: '700',
      letterSpacing: 0,
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 36,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 32,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 28,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 24,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 32,
    },
    titleLarge: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 22,
      fontWeight: '600',
      letterSpacing: 0,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 16,
      fontWeight: '600',
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 14,
      fontWeight: '600',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    bodyLarge: {
      fontFamily: 'Inter_400Regular',
      fontSize: 16,
      fontWeight: '400',
      letterSpacing: 0.5,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'Inter_400Regular',
      fontSize: 14,
      fontWeight: '400',
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'Inter_400Regular',
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    labelLarge: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 14,
      fontWeight: '600',
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.5,
      lineHeight: 16,
    },
  },
  roundness: 16,
  animation: {
    scale: 1.0,
  },
};

export default theme; 